fixes error when compiling on osx 10.9
Fixes error when compiling on osx 10.9:

In file included from Properties.cpp:3:
In file included from ./Properties.h:25:
../../src/Utils/any.h:43:16: error: implicit instantiation of undefined
template
      'std::__1::basic_string<char, std::__1::char_traits<char>,
      std::__1::allocator<char> >'
      result+= std::string(")");
               ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoo
lchain/usr/bin/../lib/c++/v1/iosfwd:187:28: note:
      template is declared here
    class _LIBCPP_TYPE_VIS basic_string;