fix undefined reference to `snprintf`
this may be deprecated in newer version than Visual C++ Express 2010
see : http://stackoverflow.com/questions/2915672/snprintf-and-visual-studio-2010